### PR TITLE
criando arquivos do k8s + shell de execução unificado

### PR DESCRIPTION
**Pull request by gabriellima09**
Relacionado a #65 

---

Texto usado no chat-gpt para gerar os arquivos:
Link para o chat gerado: https://chat.openai.com/share/fdf5e03a-c4b0-498a-968c-8585714840d4

> generate kubernetes yaml files for an application having the following information:
> 
> the k8s files should contain
> - the applications are in .net 6 
> - all files should match the namespace "techlanches". a file/command to create it is a must
> - pod for an api called techlanches-api (hosted in 5050 port internally & expose in port 80)
> - pod for an worker (background service) called techlanches-worker. the worker is a IHostedBackground service, so include the /health endpoint to it in the configs (use port 5060)
> - the images for api/worker pods are in dotnet 6, under "g12-4soat" dockerhub user and they're named techlanches-api and techlanches-worker respectively. they are public so no auth is necessary
> - pod and volumes (separate pv/pvc yaml files) for a sql server 2019 database image
> - hpa files for both api and worker having scale up to 3 pods (standart) and scale down to 1 pod when cpu and/or memory are under 50%
> - secrets to store DefaultConnection string to database that will be used for both api/worker
> - configMap in case the worker needs to communicate to the api via http requests
> - generate separate deployment files for all pods
> - generate separate loadbalancer service files for the api and worker
> - generate probes for api and worker
> - link all necessary variables (config, secrets) between these files
> 
> show the command sequences to apply all those scripts

### CODE REVIEW

**Comment by gabriellima09** [comment]
Links relacionados a health check em background services para Probes (liveness & readness)

https://github.com/rahulrai-in/worker-service-kubernetes/
https://www.bencode.net/posts/k8s-worker/

**Comment by gabriellima09** [comment]
relação de pv, pvc e storage class https://medium.com/devops-mojo/kubernetes-storage-options-overview-persistent-volumes-pv-claims-pvc-and-storageclass-sc-k8s-storage-df71ca0fccc3

**Comment by gabriellima09** [comment]
add metrics, serviceaccounts, roles, role bindings

**Comment by gabriellima09** [comment]
add definição de resources dos yamls (limites de cpu e memória)

**Comment by gabriellima09** [comment]
incluir probes

**Comment by gabriellima09** [comment]
verificar e testar se hpas sobrescrevem replicas/replicaset do deployment

**Review by aoliveiramateus — APPROVED** [review]

**Review by vitor-lupinetti — APPROVED** [review]

**Pull request merged**
